// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify.
// It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_appsync_graphqlEndpoint: 'https://yryxqaqwuvalphwuesf2mx555u.appsync-api.us-west-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-west-2',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-wsi3l32gozbkbo5vbnfydfto2a',
  aws_content_delivery_bucket: 'sc2eventswebsite-20190210211424-hostingbucket',
  aws_content_delivery_bucket_region: 'us-west-2',
  aws_content_delivery_url: 'http://sc2eventswebsite-20190210211424-hostingbucket.s3-website-us-west-2.amazonaws.com',
};


export default awsmobile;
